version: '3.1'
services:
   postgres:
      container_name: postgres-container
      image: postgres:latest
      restart: always
      environment:
         POSTGRES_PASSWORD: postgres
         POSTGRES_USER: postgres
         POSTGRES_DB: postgres
      volumes:
         - ./pgdata:/var/lib/postgres/data
      ports:
         - '5433:5432'
   api:
      container_name: developers-api
      restart: always
      build: .
      ports:
         - '4000:4000'
      depends_on:
         - postgres
